---
include:
  - board: nrfmicro_13
    shield: splitkb_zx_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
  - board: nrfmicro_13
    shield: splitkb_zx_right
  - board: nrfmicro_13
    shield: settings_reset
